# Generated by Django 4.0.1 on 2022-01-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_seller_email_remove_product_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(related_name='products', to='suppliers.Supplier'),
        ),
    ]
