# Generated by Django 4.0.1 on 2022-02-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_alter_product_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='supplier',
            new_name='suppliers',
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='notes',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
