# Generated by Django 4.0.6 on 2023-02-04 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='invoice_manager',
            new_name='suppliers',
        ),
    ]
